<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<PublishAot>true</PublishAot>
		<OptimizationPreference>Size</OptimizationPreference>
		<StackTraceSupport>false</StackTraceSupport>
		<InvariantGlobalization>true</InvariantGlobalization>
		<EventSourceSupport>false</EventSourceSupport>
		<HttpActivityPropagationSupport>false</HttpActivityPropagationSupport>
		<DebugType>none</DebugType>
		<DebugSymbols>false</DebugSymbols>
		<TrimMode>full</TrimMode>
		<IlcGenerateStackTraceData>false</IlcGenerateStackTraceData>
		<IlcOptimizationPreference>Size</IlcOptimizationPreference>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
	</PropertyGroup>

	<!-- Слияние секций и RWX: через link.exe (LinkerArg), не через ilc — иначе ilc падает. Только при publish -r win-x64. -->
	<ItemGroup Condition="'$(RuntimeIdentifier)' == 'win-x64'">
		<LinkerArg Include="/MERGE:.rdata=.shared" />
		<LinkerArg Include="/MERGE:.text=.shared" />
		<LinkerArg Include="/MERGE:.pdata=.shared" />
		<LinkerArg Include="/SECTION:.shared,RE" />
		<EmbeddedResource Include="marker.bin" LogicalName="Retention.Marker" />
	</ItemGroup>

</Project>